version: "3"
 
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: olosive-loginservice
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    command: yarn dev